"""Message protocol primitives shared by every MARGO agent."""

from core.protocol.messages import (
    AxisName,
    CohortStats,
    Directive,
    ItemAudienceProfile,
    ItemDescription,
    Message,
    MessageType,
    NegotiationLog,
    NegotiationMessage,
    NegotiationOutcome,
    PreferenceAxis,
    RankedItem,
    Rationale,
    RecommendationResult,
    TrendAlignment,
    TrendDirectiveTension,
    TrendInterpretation,
    TrendLifecycle,
    TrendPosition,
    UserPreferenceState,
    ValidationReport,
    compute_cohort_signature,
)
from core.protocol.router import MessageBus

__all__ = [
    "AxisName",
    "CohortStats",
    "Directive",
    "ItemAudienceProfile",
    "ItemDescription",
    "Message",
    "MessageType",
    "NegotiationLog",
    "NegotiationMessage",
    "NegotiationOutcome",
    "PreferenceAxis",
    "RankedItem",
    "Rationale",
    "RecommendationResult",
    "TrendAlignment",
    "TrendDirectiveTension",
    "TrendInterpretation",
    "TrendLifecycle",
    "TrendPosition",
    "UserPreferenceState",
    "ValidationReport",
    "MessageBus",
    "compute_cohort_signature",
]
